spring.config.import=optional:file:.env[.properties]
spring.application.name=backend-core

# ===============================
# SERVER PORT
# ===============================
server.port=${SERVER_PORT:8080}

# ===============================
# POSTGRESQL DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_HOST_PORT:5433}/${POSTGRES_DB:1clickdb}
spring.datasource.username=${POSTGRES_USER:1click}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

# ===============================
# REDIS / RABBITMQ CONFIGURATION
# ===============================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_HOST_PORT:6379}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_HOST_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:1click}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:}

# ===============================
# HIBERNATE / JPA CONFIGURATION
# ===============================
# Automatically creates and updates database tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Show SQL queries in the console (great for learning how Hibernate works)
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

# Specify the exact PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
